#!/bin/bash

# Manual Setup Commands for Android Project
# Run these commands one by one in your terminal

echo "=========================================="
echo "Android Project Manual Setup"
echo "=========================================="
echo ""
echo "Step 1: Install Java JDK 11"
echo "Run: sudo apt update && sudo apt install -y openjdk-11-jdk"
echo ""
echo "Step 2: Set JAVA_HOME"
echo "Run: export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
echo "Run: export PATH=\$PATH:\$JAVA_HOME/bin"
echo ""
echo "Step 3: Verify Java Installation"
echo "Run: java -version"
echo "Run: javac -version"
echo ""
echo "Step 4: Navigate to Project"
echo "Run: cd /home/layth/Documents/razzan/Androidfyp-main/android"
echo ""
echo "Step 5: Make Gradle Wrapper Executable"
echo "Run: chmod +x gradlew"
echo ""
echo "Step 6: Build the Project"
echo "Run: ./gradlew build"
echo ""
echo "Step 7: Build Debug APK"
echo "Run: ./gradlew assembleDebug"
echo ""
echo "Step 8: Check for Android SDK (if you have it)"
echo "Run: echo \$ANDROID_HOME"
echo "Run: adb devices"
echo ""
echo "Step 9: Install on Device (if device connected)"
echo "Run: ./gradlew installDebug"
echo ""
echo "=========================================="
echo "To make JAVA_HOME permanent, add to ~/.bashrc:"
echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
echo "export PATH=\$PATH:\$JAVA_HOME/bin"
echo "=========================================="
